version: '2'
services:
 unifi-controller:
   container_name: unifi.controller-5.7.23
   image: jacobalberty/unifi:5.7.23
   volumes:
     - './data:/unifi/data'
     - './log:/unifi/log'
   ports:
     - '3478:3478/udp'
     - '10001:10001/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
   environment:
     - TZ=Europe/Warsaw
     - RUNAS_UID0=false
     - UNIFI_UID=1000
     - UNIFI_GID=1000
   labels:
     - 'unifi-controller'
